// Copies the AllStar knowledge base into the chat function bundle.
// Usage: npm run sync-kb            (uses default path below)
//        npm run sync-kb -- "/path/to/allstar-knowledge-base.md"
//
// Writes:
//   netlify/functions/knowledge/allstar-knowledge-base.md   (verbatim copy)
//   netlify/functions/knowledge/allstar-knowledge-base.mjs  (string the function imports)
//
// The .mjs drops the "What the site says" column of the NEEDS JAMAL TO CONFIRM
// table so the bot only ever sees the "Safe answer" text, never the conflicting facts.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { homedir } from 'node:os';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const outDir = join(here, '..', 'netlify', 'functions', 'knowledge');
const src = process.argv[2]
  || process.env.KB_SOURCE
  || join(homedir(), 'mnt', 'AllStar Online', 'allstar-knowledge-base.md');

const raw = readFileSync(src, 'utf8');

const cleaned = raw.split('\n').map((line) => {
  // Table rows look like: | # | Topic | What the site says | Safe answer |
  const m = line.match(/^\|\s*(\d+)\s*\|(.*)\|\s*$/);
  if (!m) return line;
  const cells = line.split('|').slice(1, -1).map((c) => c.trim());
  if (cells.length !== 4) return line;
  return `- Confirm #${cells[0]} ${cells[1]}: SAFE ANSWER = ${cells[3]}`;
}).filter((l) => !/^\|\s*#\s*\|/.test(l) && !/^\|[-\s|]+\|$/.test(l));

mkdirSync(outDir, { recursive: true });
writeFileSync(join(outDir, 'allstar-knowledge-base.md'), raw);
writeFileSync(
  join(outDir, 'allstar-knowledge-base.mjs'),
  '// GENERATED by scripts/sync-chat-kb.mjs. Do not edit by hand.\n' +
  'export default ' + JSON.stringify(cleaned.join('\n')) + ';\n'
);
console.log(`KB synced from ${src} (${raw.length} chars)`);
